Fixed all possible TODO
microservices-course-itmo/catalog-service pull request #1
Opened 2020-09-22 18:32 UTC by YRaphael

Fixed all the todo that I could (some of them are not fixed due to the lack of catalog-service-api).

2020-09-22 18:36 UTC, YRaphael commented
Wrong assigners

2020-09-23 15:22 UTC, shinehlina requested changes

2020-09-23 15:22 UTC, shinehlina commented on pom.xml
>          <current-version>0.2.0</current-version>
Лучше 0.1.0

2020-09-23 15:23 UTC, shinehlina approved these changes, later dismissed

2020-09-24 01:05 UTC, AfanasievYuriy approved these changes, later dismissed

2020-09-28 13:16 UTC, merged